[phases.setup]
nixpkgs = [
  "rust-bin.stable.latest.default", 
  "binutils",
  "gcc",
  "glibc",
  "glibc.dev"
]

[phases.build]
cmds = [
  "git clone --depth 1 https://github.com/visioncortex/vtracer.git /tmp/vtracer",
  "cargo build --release --manifest-path /tmp/vtracer/Cargo.toml",
  "cargo install --path /tmp/vtracer/cmdapp",
  "mkdir -p /app/bin",
  "cp /root/.cargo/bin/vtracer /app/bin/vtracer",
  "chmod +x /app/bin/vtracer",
  "rm -rf /tmp/vtracer"
]

[start]
cmd = "/app/bin/vtracer"
runImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1745885067"

[env]
RUST_LOG = "info,tower_http=info"
PORT = "8080"