[phases.setup]
nixpkgs = "https://github.com/NixOS/nixpkgs/archive/a683adc19ff5228af548c6539dbc3440509bfed3.tar.gz"
nixPkgs = [
  "rustc",
  "cargo",
  "pkg-config",
  "openssl",
  "gcc",
  "gnumake",
  "zlib",
  "libpng",
  "libjpeg",
  "freetype",
  "libtiff",
  "libwebp"
]

[phases.build]
cmds = [
  "cargo build --release",
  "git clone --depth 1 https://github.com/visioncortex/vtracer.git /tmp/vtracer",
  "cd /tmp/vtracer && cargo install --path cmdapp",
  "cp /root/.cargo/bin/vtracer /usr/local/bin/vtracer",
  "chmod +x /usr/local/bin/vtracer",
  "rm -rf /tmp/vtracer"
]

[start]
cmd = "./target/release/vtracer-api"

[env]
RUST_LOG = "info,tower_http=info"
PORT = "8080"
