[phases.setup]
nixpkgs = [
  "rust-bin.stable.latest.default.override { targets = [\"x86_64-unknown-linux-gnu\"]; }",
  "binutils",
  "gcc",
  "glibc",
  "glibc.dev"
]

[phases.build]
cmds = [
  "git clone --depth 1 https://github.com/visioncortex/vtracer.git /tmp/vtracer",
  "cargo build --release --target x86_64-unknown-linux-gnu --manifest-path /tmp/vtracer/Cargo.toml",
  "cargo install --path /tmp/vtracer/cmdapp --target x86_64-unknown-linux-gnu",
  "mkdir -p /app/bin",
  "cp /tmp/vtracer/target/x86_64-unknown-linux-gnu/release/vtracer-api /app/bin/vtracer-api",
  "cp $(cargo bin-dir)/vtracer /app/bin/vtracer",
  "chmod +x /app/bin/vtracer-api /app/bin/vtracer",
  "rm -rf /tmp/vtracer"
]

[start]
cmd = "/app/bin/vtracer-api"
runImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1745885067"

[env]
RUST_LOG = "info,tower_http=info"
PORT = "8080"