[phases.setup]
nixPkgs = [
  "python312",
  "python312Packages.pip",
  "python312Packages.setuptools",
  "python312Packages.wheel",
  "python312Packages.virtualenv"
]

[phases.build]
cmds = [
  "pip install -r requirements.txt"
]

[start]
cmd = "python main.py"

[env]
PORT = "8080"
PYTHONUNBUFFERED = "1"