[phases.setup]
nixpkgs = [
  "rust-bin.stable.latest.default.override { targets = [\"x86_64-unknown-linux-gnu\"] ; }",
  "binutils",
  "gcc",
  "glibc",
  "glibc.dev"
]

[phases.build]
cmds = [
  "git clone --depth 1 https://github.com/visioncortex/vtracer.git /tmp/vtracer",
  "rustup target add x86_64-unknown-linux-gnu",
  "cd /tmp/vtracer && cargo build --release --target x86_64-unknown-linux-gnu",
  "cd /tmp/vtracer && cargo install --path cmdapp --target x86_64-unknown-linux-gnu",
  "cp /root/.cargo/bin/vtracer /usr/local/bin/vtracer",
  "chmod +x /usr/local/bin/vtracer",
  "mkdir -p /app/bin",
  "cp /tmp/vtracer/target/x86_64-unknown-linux-gnu/release/vtracer-api /app/bin/vtracer-api",
  "chmod +x /app/bin/vtracer-api",
  "rm -rf /tmp/vtracer"
]

[start]
cmd = "/app/bin/vtracer-api"
runImage = "ghcr.io/railwayapp/nixpacks:ubuntu-1745885067"

[env]
RUST_LOG = "info,tower_http=info"
PORT = "8080"